name: List Files in Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Files
        run: ls -R
