name: Create GitHub Release and Upload Assets
on:
  push:
    tags:

      - 'v*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js (if needed for build)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      # Optional: Build your project and create assets
      - name: Build project
        run: |
          npm ci
          npm run build
          # Ensure your assets are in ./dist
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: "Automated release for tag ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.zip
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
