name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      - name: Deploy Container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-app:latest
