name: Trigger Target Repo Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Required Variables
        run: |
          repo_owner="target-repo-owner"
          repo_name="target-repo-name"
          event_type="trigger-workflow"
          service="demo-app"
          version="v1.0.0"

      - name: Trigger Workflow in Target Repository
        run: |
          curl -L \
          -X POST \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
          -d '{"event_type": "'"$event_type"'", "client_payload": {"service": "'"$service"'", "version": "'"$version"'"}}'
